version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
           fingerprints:
             - "04:f5:3f:d8:0f:ad:71:fe:fd:42:88:bd:3f:4d:9d:4b"
      - run:
          name: fix host authenticity for production server
          command: ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
      - run:
          name: ssh
          command: ssh $SSH_USER@$SSH_HOST "uname -a"
