version: 2 # use CircleCI 2.0
defaults: &defaults
  working_directory: ~/circleci-demo-java-spring
  docker:
    - image: circleci/openjdk:9-jdk
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    <<: *defaults    
    steps: # a collection of executable commands

      - checkout # check out source code to working directory

      - run: mvn package -Dmaven.test.skip=true
      
      - store_test_results: # uploads the test metadata from the `target/surefire-reports` directory so that it can show up in the CircleCI dashboard. 
          path: target/surefire-reports
      
      - store_artifacts: # store the uberjar as an artifact
          path: /home/circleci/circleci-demo-java-spring/target/dist/tale.tar.gz
      - persist_to_workspace:
          root: ~/circleci-demo-java-spring
          paths: .
  deploy:
    machine:
      enabled: true
    steps:
      - attach_workspace:
          at: ~/circleci-demo-java-spring
      - run:
          name: untar
          command: tar -xvf ~/circleci-demo-java-spring/target/dist/tale.tar.gz -C ~/circleci-demo-java-spring/APP/opt/src
      - run:
          name: Push deb package
          command: find . -type f ! -regex 'md5sum.sh' ! -regex '.*.hg.*' ! -regex '.*?debian-binary.*' ! -regex '.*?DEBIAN.*' -printf '%P ' | xargs md5sum > DEBIAN
      - run:
          name: build
          command: fakeroot dpkg-deb --build ~/circleci-demo-java-spring/APP

workflows:
  version: 2
  package-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
