version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  deploy:
    machine:
      enabled: true
    steps:
     - add_ssh_keys:
          fingerprints:
            - "96:4e:9e:63:c5:19:dd:00:15:2e:10:b6:35:a7:8c:5e"
      - run:
          name: ssh
          command: ssh $SSH_USER@$SSH_HOST "uname -a"

workflows:
  version: 2
  package-deploy:
    jobs:
      - deploy:
